### PR TITLE
fixed the distribution in quickstart

### PR DESCRIPTION
**Pull request by bluest93**
# Change
fixed the issue in the distribution plot in `quickstart.ipynb`

# Description 
#76

### CODE REVIEW

**Review by Jacomichi — CHANGES_REQUESTED** [review]
I have rewritten your code (below).
Changes
- dictionary name
- xlabel name
- `plt.bar` part

Can you change?
```python
from collections import defaultdict
import matplotlib.pyplot as plt

sampleset = qaoa_converter.decode(qk_transpiler, job_result.data["meas"])

# Initialize a dictionary to accumulate occurrences for each energy value
frequencies = defaultdict(int)

# Define the precision to which you want to round the energy values
for sample in sampleset:
    energy = round(sample.eval.objective, ndigits = 3)  
    frequencies[energy] += sample.num_occurrences

plt.bar(frequencies.keys(), frequencies.values(), width=0.05)
plt.xlabel('Objective')
plt.ylabel('Frequency')
plt.show()
```

**Comment by Jacomichi** [comment]
Can you also change #87 ?

**Comment by bluest93** [comment]
Updated the code

**Review by Jacomichi — APPROVED** [review]
LGTM

**Pull request merged**
